"""refine models for smart import

Revision ID: 2764984cda81
Revises: 73eba101e38f
Create Date: 2026-02-17 21:45:58.604814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2764984cda81'
down_revision = '73eba101e38f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_of_measure', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cost_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('selling_price', sa.Float(), nullable=True))
        batch_op.alter_column('quantity_on_hand',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internal_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('size_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('size_unit', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pack_quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pack_unit', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('local_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('sku',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('local_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('barcode',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_product_sku'), ['sku'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_sku'))
        batch_op.alter_column('category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('barcode',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('local_code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('sku',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('local_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('pack_unit')
        batch_op.drop_column('pack_quantity')
        batch_op.drop_column('size_unit')
        batch_op.drop_column('size_value')
        batch_op.drop_column('internal_code')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('quantity_on_hand',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('selling_price')
        batch_op.drop_column('cost_price')
        batch_op.drop_column('unit_of_measure')

    # ### end Alembic commands ###
