"""add user display preferences

Revision ID: 679953aaef48
Revises: a6e891676abc
Create Date: 2026-02-22 22:17:42.165633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679953aaef48'
down_revision = 'a6e891676abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chart_style', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('landing_page', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('landing_page')
        batch_op.drop_column('chart_style')

    # ### end Alembic commands ###
