"""Add is_denied to User table

Revision ID: 781ac70b3bf7
Revises: 305913cbcbe0
Create Date: 2026-03-04 12:48:36.321081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781ac70b3bf7'
down_revision = '305913cbcbe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sale', ['sale_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_denied', sa.Boolean(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_denied')

    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sale_id')
    # ### end Alembic commands ###
