"""Add size and pack fields to Inventory

Revision ID: c5fb274d8f97
Revises: 2764984cda81
Create Date: 2026-02-17 22:40:38.310130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5fb274d8f97'
down_revision = '2764984cda81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_size', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('unit_measure', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pack_qty', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pack_unit', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('extra_info', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('extra_info')
        batch_op.drop_column('pack_unit')
        batch_op.drop_column('pack_qty')
        batch_op.drop_column('unit_measure')
        batch_op.drop_column('unit_size')

    # ### end Alembic commands ###
