"""Remove pricing from inventory

Revision ID: fa4db74fead6
Revises: c5fb274d8f97
Create Date: 2026-02-18 00:16:32.098147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa4db74fead6'
down_revision = 'c5fb274d8f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('selling_price')
        batch_op.drop_column('cost_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('selling_price', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
